### ISSUE TITLE
Test countingBloomFIlter remove element  on error

### ISSUE THREAD

**Issue by yelllowhat** [francois/hadoop-bloomfilter#2]
Thanks for your reply, I may be not clear, we test, adding 10 elements, and then delete the 10 elements, followed by testing whether to delete, delete is the impact on the other elements.

```
@Test
public void testBasics() {
    final CountingBloomFilter cbf = new CountingBloomFilter(10, 2,
            Hash.MURMUR_HASH);

    for (int i = 0; i < 10; i++) {
        Key key = new Key(("abc" + i).getBytes(UTF8));
        cbf.add(key);
    }

    String keyStr = null;
    for (int i = 0; i < 10; i++) {
        keyStr = "abc" + i;
        Key key = new Key(keyStr.getBytes(UTF8));
        //assertTrue("key present after insertion", cbf.membershipTest(key));
        System.out.println("delete before , member ship test key : " + keyStr + " , " + cbf.membershipTest(key));

        cbf.delete(key);
        //assertFalse("key gone after deletion", cbf.membershipTest(key));
        System.out.println("delete after , member ship test key : " + keyStr + " , " + cbf.membershipTest(key));
    }
}
```

   result : 

delete before , member ship test key : abc0 , true
delete after , member ship test key : abc0 , true
delete before , member ship test key : abc1 , true
delete after , member ship test key : abc1 , true
delete before , member ship test key : abc2 , true
delete after , member ship test key : abc2 , true
delete before , member ship test key : abc3 , true
delete after , member ship test key : abc3 , false
delete before , member ship test key : abc4 , true
delete after , member ship test key : abc4 , true
delete before , member ship test key : abc5 , true
delete after , member ship test key : abc5 , false
delete before , member ship test key : abc6 , true
delete after , member ship test key : abc6 , false
delete before , member ship test key : abc7 , true
delete after , member ship test key : abc7 , true
delete before , member ship test key : abc8 , true
delete after , member ship test key : abc8 , false
delete before , member ship test key : abc9 , true
delete after , member ship test key : abc9 , false

Why add to delete, the added value is still? Delete and also for other results have error influence ?

for example 

delete before , member ship test key : abc0 , true
delete after , member ship test key : abc0 , true
........

The correct result should be like this, to join the deleted, again looking for should return false, it returns the true here, said there was no real delete !

**Comment by francois** [comment]
As I said before, I am not the maintainer. I extracted the Bloom Filter implementation from the Hadoop project, and made it available here. If you have issues with how the Bloom Filter works, please move the discussion over to the [Hadoop common mailing list](https://hadoop.apache.org/mailing_lists.html#Common). Feel free to link back here for your test case.
